merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.band_list,name="band-list"),
    path("bands/<int:id>",views.band_detail,name="band-detail"),
    path("contact",views.contact,name="contact_us"),
    path("email-send",views.email_send,name="email-envoyer"),
    path('bands/add/', views.band_create, name='band-create'),
    ]

merchex/listings/models.py
from pyexpat import model
from unicodedata import name
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator



# Create your models here.
class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP ="HH"
        SYNTH_POP = "SP"
        ALTERNATIVE_ROCK = "AR"
    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biographie = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900),MaxValueValidator(2021)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    def __str__(self):
        return f'{self.name}'

class Listing(models.Model):
    class ListingType(models.TextChoices):
        RECORDS ="R"
        CLOTHING = "C"
        POSTERS = "P"
        MISC = "M"
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(  
        null = True,
        validators=[MinValueValidator(1900),
                    MaxValueValidator(2021)]
                    )
    type = models.fields.CharField(choices=ListingType.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return f'{self.title}'
    

merchex/listings/views.py
from audioop import reverse
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from listings.models import Band
from listings.form_contact import ContactUsForm ,BandForm
from django.shortcuts import redirect  
from django.core.mail import send_mail

# ajoutez cet import
# Create your views here.

def band_list(request):
    bands  = Band.objects.all()
    return render (request,'listings/band_list.html',context ={"bands":bands})


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                    'listings/band_detail.html',
                    {'band':band})
	
def about(request):
    return render(request,'listings/about.html')
def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
           send_mail(
             subject=f'Message from {form.cleaned_data["nom"] or "anonyme"} via MerchEx Contact Us form',
             message=form.cleaned_data['message'],
                 from_email=form.cleaned_data['email'],
             recipient_list=['admin@merchex.xyz'],
        )

        return redirect("email-envoyer")

    else:
        form = ContactUsForm()
    
    return render(request,
                  'listings/contact.html',
                  {'form':form})
def email_send(request):
    return render(request,"listings/email_send.html")

def band_create(request):
    if request.method == "POST":
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else: form =BandForm()
    return render(request,'listings/band_create.html',{'form':form})

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Créer un nouveau groupe</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends "listings/base.html" %}
{% block content %}

<h1>{{band.name}}</h1>
<ul>
    <li>Genre: {{band.get_genre_display}}</li>
    <li>Date de creation : {{ band.year_formed }}</li>
    <li>Active : {{band.active|yesno}}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage}}">{{ band.official_homepage }}</a></li>
    {% endif %}
</ul>
<p>{{ band.biographie }}</p>

<br>
<br>

<br>
<br>
<a href="{%url 'band-list'%}"><h1>retour</h1></a>
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends "listings/base.html" %}
{% block content %}

<ul>
    {% for band in bands %}
        <a href="{% url 'band-detail' band.id %}"><li>{{band.name}}</li></a>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/base.html
<!DOCTYPE html>

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'listings/style.css'%}">
    <title>merchex</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

merchex/listings/templates/listings/contact.html
{% extends "listings/base.html" %}
{% block content %}


<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
{% csrf_token %}
{{ form }}
<input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/email_send.html
{% extends "listings/base.html" %}
{% block content %}

<h1>bravo </h1>
{% endblock %}